name: Badge SPF Action
description: An action for generating a badge using SimplePixelFonts

inputs:
  label:
    description: The label to use for the badge
    required: true
    default: "Tests"

  message:
    description: The message to use for the badge
    required: true
    default: "Passing"

  color:
    description: The color to use for the badge
    required: true
    default: "#00bfa3"

  labelColor:
    description: The color to use for the label
    required: true
    default: "#2d3136"

  filename:
    description: The filename to write the badge to
    required: true
    default: "./badge.png"

  logo:
    description: The logo to use for the badge
    required: true
    default: "https://raw.githubusercontent.com/The-Nice-One/GalleryArt/refs/heads/main/base_emojis/wrench.png"

  font:
    description: The font to use for the badge
    required: true
    default: "https://raw.githubusercontent.com/SimplePixelFont/web-spf/refs/heads/main/Monogram-light.spf"

runs:
  using: node20
  main: dist/index.js

